language: node_js
node_js: 
- '10'

before_install: 
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master

# change for deploy service
deploy:
  provider: heroku
  api_key: 
    secure: "f06e7e15-e400-427b-bee9-bb3bfa875e90"
  app: mazeangular